/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ContentStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Text,
  'status' : ContentStatus,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'coverImage' : IDL.Opt(ExternalBlob),
  'updatedAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [Article],
      [],
    ),
  'getAllArticles' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getArticleById' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(Article)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'publishArticle' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Article], []),
  'resetDefaultAdminCredential' : IDL.Func([], [], []),
  'unpublishArticle' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Article], []),
  'updateArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [Article],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ContentStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Text,
    'status' : ContentStatus,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'coverImage' : IDL.Opt(ExternalBlob),
    'updatedAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [Article],
        [],
      ),
    'getAllArticles' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getArticleById' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(Article)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'publishArticle' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Article], []),
    'resetDefaultAdminCredential' : IDL.Func([], [], []),
    'unpublishArticle' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Article], []),
    'updateArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
        ],
        [Article],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };