/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : string,
  'status' : ContentStatus,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'coverImage' : [] | [ExternalBlob],
  'updatedAt' : Time,
}
export type ContentStatus = { 'published' : null } |
  { 'draft' : null };
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<
    [string, string, [] | [ExternalBlob], [] | [string]],
    Article
  >,
  'getAllArticles' : ActorMethod<[[] | [string]], Array<Article>>,
  'getArticleById' : ActorMethod<[string, [] | [string]], [] | [Article]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublishedArticles' : ActorMethod<[], Array<Article>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], string>,
  'logout' : ActorMethod<[string], undefined>,
  'publishArticle' : ActorMethod<[string, [] | [string]], Article>,
  /**
   * / Overwrite current admin credentials with default admin account
   * / SECURITY: This function requires admin authorization when credentials already exist.
   * / For first-time setup, it requires the caller to be an admin via AccessControl.
   */
  'resetDefaultAdminCredential' : ActorMethod<[], undefined>,
  'unpublishArticle' : ActorMethod<[string, [] | [string]], Article>,
  'updateArticle' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], [] | [string]],
    Article
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];